mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'puppetlabs/powershell' 
mod 'stahnma-epel', '1.3.1'
mod 'puppet-yum', '4.0.0'
mod 'theforeman-foreman', '13.1.0'
mod 'puppetlabs-apache', '5.2.0'
mod 'puppetlabs-postgresql', '6.2.0'
mod 'puppet-extlib', '4.1.0'
